In [1]:
import pandas as pd

In [2]:
fp = 'data/029740.txt'
df = pd.read_csv(fp, delim_whitespace=True, usecols=['YR--MODAHRMN', 'TEMP'], na_values=['*', '**', '***', '****', '*****', '******'], parse_dates=True, index_col='YR--MODAHRMN')

In [3]:
df['TEMP_C'] = (df['TEMP'] - 32) / 1.8

In [4]:
df['Month'] = df.index.month.values
df['Year'] = df.index.year.values

In [5]:
grouped = df.groupby(["Year", "Month"])

In [6]:
grouped

In [7]:
df[grouped]

ValueError: cannot copy sequence with size 116 to array axis with dimension 4

In [8]:
grouped.get_group((1952,1))

TEMP    TEMP_C  Month  Year
YR--MODAHRMN                                    
1952-01-01 00:00:00  36.0  2.222222      1  1952
1952-01-01 06:00:00  37.0  2.777778      1  1952
1952-01-01 12:00:00  39.0  3.888889      1  1952
1952-01-01 18:00:00  36.0  2.222222      1  1952
1952-01-02 00:00:00  36.0  2.222222      1  1952
...                   ...       ...    ...   ...
1952-01-30 06:00:00  25.0 -3.888889      1  1952
1952-01-30 12:00:00  27.0 -2.777778      1  1952
1952-01-30 18:00:00  23.0 -5.000000      1  1952
1952-01-31 12:00:00  30.0 -1.111111      1  1952
1952-01-31 18:00:00  28.0 -2.222222      1  1952

[116 rows x 4 columns]

In [9]:
years = df.index.year.unique().values

In [10]:
years

array([1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962,
       1963, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019])

In [11]:
years_ok = []
for i in range(len(years)):
    if years[i]-1 in years:
        years_ok.append(years[i])


In [12]:
import numpy as np

winter_means = np.zeros(len(years_ok))
winter_std = np.zeros(len(years_ok))
summer_means = np.zeros(len(years_ok))
summer_std = np.zeros(len(years_ok))

    

In [13]:
df.loc[(df.index >= '19521201') & (df.index < '19530301')]

TEMP    TEMP_C  Month  Year
YR--MODAHRMN                                    
1952-12-01 00:00:00  19.0 -7.222222     12  1952
1952-12-01 06:00:00  23.0 -5.000000     12  1952
1952-12-01 12:00:00  25.0 -3.888889     12  1952
1952-12-01 18:00:00  23.0 -5.000000     12  1952
1952-12-02 00:00:00  21.0 -6.111111     12  1952
...                   ...       ...    ...   ...
1953-02-27 18:00:00  36.0  2.222222      2  1953
1953-02-28 00:00:00  32.0  0.000000      2  1953
1953-02-28 06:00:00  28.0 -2.222222      2  1953
1953-02-28 12:00:00  37.0  2.777778      2  1953
1953-02-28 18:00:00  30.0 -1.111111      2  1953

[351 rows x 4 columns]

In [14]:
for i in range(len(years_ok)):
    winter_min = str(years_ok[i]-1)+'1201'
    winter_max = str(years_ok[i])+'0301'
    summer_min = str(years_ok[i])+'0601'
    summer_max = str(years_ok[i])+'0901'
    winter_means[i] = df['TEMP_C'].loc[(df.index >= winter_min) & (df.index < winter_max)].mean()
    winter_std[i] = df['TEMP_C'].loc[(df.index >= winter_min) & (df.index < winter_max)].std()
    summer_means[i] = df['TEMP_C'].loc[(df.index >= summer_min) & (df.index < summer_max)].mean()
    summer_std[i] = df['TEMP_C'].loc[(df.index >= summer_min) & (df.index < summer_max)].std()

In [15]:
winter_means

array([ -5.60025543,  -6.24444444,  -4.4301178 , -10.64090177,
        -2.57024266,  -6.52006173,  -4.38403644,  -8.22605965,
        -1.47893306,  -4.63261649,  -9.10538045,  -3.27908468,
        -1.17736553,  -6.25303377,  -6.38210821,  -6.77054446,
       -10.22978901,  -7.11157263,  -4.38368473,  -7.399796  ,
        -3.13323146,  -4.14394943, -10.69556977,  -8.563499  ,
       -10.69224869,  -3.70719322,  -2.11242631,  -2.63154828,
        -3.33916288,  -1.60824046,  -1.29926474,  -6.12576715,
        -1.30043174,  -7.91561495,  -4.15535445,  -3.04365666,
        -4.60956235,  -2.41778689,  -2.78577559,  -3.85808967,
        -7.94381364,  -4.29424033,  -2.29827249,  -5.74626998,
        -2.70581282,   0.53403034,  -2.78715025,  -8.97884585,
        -8.58880967,  -3.5559125 ,  -5.1677377 ,  -2.21456591,
        -0.94466026,  -2.90848668,  -2.2631896 ,  -3.17508418,
        -2.88874673])

In [16]:
winter_std

array([6.12686433, 6.80412778, 6.12855747, 8.52118471, 3.81924241,
       7.54857093, 5.51404968, 6.46576097, 4.17624499, 5.60464355,
       6.75292271, 5.76488736, 4.74825277, 6.71703193, 6.34526635,
       6.50649979, 7.30104317, 7.02292129, 5.34506902, 6.35616373,
       5.60191536, 5.42544798, 8.64428239, 6.4084586 , 9.47737652,
       5.09969027, 5.33581282, 6.13214605, 5.14168517, 4.42451519,
       4.58169832, 6.55457806, 3.74275019, 6.27819891, 6.23237063,
       5.44898912, 7.04995365, 4.93344352, 7.12542655, 6.21989467,
       7.56102   , 5.56662857, 4.95386552, 6.56039215, 7.69141596,
       3.0227173 , 4.60137027, 6.7289793 , 6.97194079, 6.77873736,
       5.02227022, 6.5422391 , 4.45052479, 7.8547964 , 5.11901278,
       5.70360563, 5.25836357])

In [17]:
summer_means

array([16.40605493, 15.29247911, 16.21813031, 14.64162754, 15.35555556,
       14.42330918, 16.6017094 , 16.43997939, 15.62318841, 13.21136292,
       16.02393406, 14.95234674, 15.94204971, 14.69587974, 14.65558332,
       14.49489784, 15.65865289, 15.72357502, 14.57327713, 14.79916644,
       15.81156317, 14.78534557, 15.16061902, 15.90822269, 13.51957941,
       16.62871852, 16.04943376, 15.34976936, 15.84377778, 15.95704115,
       13.48103283, 16.07727522, 16.57249201, 15.34916341, 17.87776757,
       14.85019015, 17.77877923, 15.66433833, 17.09732072, 18.54996661,
       16.5416694 , 15.40280249, 16.36502482, 17.84416225, 16.78732493,
       15.49676973, 15.81858444, 18.3676915 , 18.36256423, 15.70229962,
       17.68006531, 17.04142611, 15.54756256, 16.30757261, 15.09220874,
       18.25151433, 17.07420894])

In [18]:
summer_std

array([3.93463592, 3.89038486, 5.34733707, 4.10136938, 4.52085698,
       4.13482814, 5.24165019, 4.0757058 , 4.06520689, 3.64554236,
       3.98546405, 3.69544994, 5.12326917, 4.31514738, 4.45182544,
       4.37366696, 3.68509432, 4.40863279, 3.81943816, 5.11709079,
       4.94216335, 4.13041292, 4.09168296, 4.49497601, 3.92310115,
       4.49120094, 4.66224188, 3.97549783, 4.41356877, 4.53470339,
       3.90255981, 5.45272359, 4.59670544, 4.15726113, 4.67771693,
       3.59973289, 4.87489448, 3.88832141, 4.67293628, 4.17789642,
       5.22367227, 4.1304242 , 4.31308101, 4.80178326, 4.52786106,
       3.8755093 , 4.55968417, 5.5500134 , 4.56483527, 4.08837055,
       4.23193991, 5.475366  , 4.03958788, 3.79499886, 4.04932822,
       5.22482784, 4.5060442 ])

In [19]:
df2 = pd.DataFrame(data={'Year': years_ok, 'Winter mean': winter_means, 'Winter std': winter_std,
                                         'Summer mean': summer_means, 'Summer std': summer_std})

In [20]:
df2

Year  Winter mean  Winter std  Summer mean  Summer std
0   1953    -5.600255    6.126864    16.406055    3.934636
1   1954    -6.244444    6.804128    15.292479    3.890385
2   1955    -4.430118    6.128557    16.218130    5.347337
3   1956   -10.640902    8.521185    14.641628    4.101369
4   1957    -2.570243    3.819242    15.355556    4.520857
5   1958    -6.520062    7.548571    14.423309    4.134828
6   1959    -4.384036    5.514050    16.601709    5.241650
7   1960    -8.226060    6.465761    16.439979    4.075706
8   1961    -1.478933    4.176245    15.623188    4.065207
9   1962    -4.632616    5.604644    13.211363    3.645542
10  1963    -9.105380    6.752923    16.023934    3.985464
11  1974    -3.279085    5.764887    14.952347    3.695450
12  1975    -1.177366    4.748253    15.942050    5.123269
13  1976    -6.253034    6.717032    14.695880    4.315147
14  1977    -6.382108    6.345266    14.655583    4.451825
15  1978    -6.770544    6.506500    14.494898    4.373667
16  1979   -10.229789    7.301043    15.658653    3.685094
17  1980    -7.111573    7.022921    15.723575    4.408633
18  1981    -4.383685    5.345069    14.573277    3.819438
19  1982    -7.399796    6.356164    14.799166    5.117091
20  1983    -3.133231    5.601915    15.811563    4.942163
21  1984    -4.143949    5.425448    14.785346    4.130413
22  1985   -10.695570    8.644282    15.160619    4.091683
23  1986    -8.563499    6.408459    15.908223    4.494976
24  1987   -10.692249    9.477377    13.519579    3.923101
25  1988    -3.707193    5.099690    16.628719    4.491201
26  1989    -2.112426    5.335813    16.049434    4.662242
27  1990    -2.631548    6.132146    15.349769    3.975498
28  1991    -3.339163    5.141685    15.843778    4.413569
29  1992    -1.608240    4.424515    15.957041    4.534703
30  1993    -1.299265    4.581698    13.481033    3.902560
31  1994    -6.125767    6.554578    16.077275    5.452724
32  1995    -1.300432    3.742750    16.572492    4.596705
33  1996    -7.915615    6.278199    15.349163    4.157261
34  1997    -4.155354    6.232371    17.877768    4.677717
35  1998    -3.043657    5.448989    14.850190    3.599733
36  1999    -4.609562    7.049954    17.778779    4.874894
37  2000    -2.417787    4.933444    15.664338    3.888321
38  2001    -2.785776    7.125427    17.097321    4.672936
39  2002    -3.858090    6.219895    18.549967    4.177896
40  2003    -7.943814    7.561020    16.541669    5.223672
41  2004    -4.294240    5.566629    15.402802    4.130424
42  2005    -2.298272    4.953866    16.365025    4.313081
43  2006    -5.746270    6.560392    17.844162    4.801783
44  2007    -2.705813    7.691416    16.787325    4.527861
45  2008     0.534030    3.022717    15.496770    3.875509
46  2009    -2.787150    4.601370    15.818584    4.559684
47  2010    -8.978846    6.728979    18.367692    5.550013
48  2011    -8.588810    6.971941    18.362564    4.564835
49  2012    -3.555912    6.778737    15.702300    4.088371
50  2013    -5.167738    5.022270    17.680065    4.231940
51  2014    -2.214566    6.542239    17.041426    5.475366
52  2015    -0.944660    4.450525    15.547563    4.039588
53  2016    -2.908487    7.854796    16.307573    3.794999
54  2017    -2.263190    5.119013    15.092209    4.049328
55  2018    -3.175084    5.703606    18.251514    5.224828
56  2019    -2.888747    5.258364    17.074209    4.506044

In [21]:
df2.to_csv('seasonal_temps2.csv', index=False, float_format='%.6f')